Settings:
  min-deposit: 10000
  colors:
    primary: "&6"
    secondary: "&e"

Funds:
  fix:
    amount: 100000
    blocked-commands:
      - 'fix'
      - 'repair'
    reward-commands:
      - 'give {PLAYER} diamond 1'
    message: "&6&lUnlock /fix [&7%percent%%&6&l] &2&l100k"
    complete-message:
      - ''
      - '&6&l(!) &eYou have all unlocked &6/fix&e as a usable command via /funds!'
      - ''
  heal:
    amount: 200000
    blocked-commands:
      - 'heal'
    reward-commands:
      - 'give {PLAYER} diamond 1'
    message: "&6&lUnlock /heal [&7%percent%%&6&l] &2&l200k"
    complete-message:
      - ''
      - '&6&l(!) &eYou have all unlocked &6/heal&e as a usable command via /funds!'
      - ''